version: '3.8'
services:
  web:
    build: .
    container_name: cyjiang-website
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app/web
    environment:
      - GO_ENV=production
    restart: always
    