services:
  web:
    build:
      context: .
      target: builder
    container_name: cyjiang-website-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GO_ENV=development
    command: go run ./main.go
    